package com.recipenotes.data.repository

import com.recipenotes.data.local.dao.RecipeDao
import com.recipenotes.data.local.dao.ShoppingItemDao
import com.recipenotes.data.local.entity.ShoppingItemEntity
import com.recipenotes.domain.model.ShoppingItem
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import javax.inject.Inject

/**
 * Repository for shopping list operations, including the auto-generation
 * algorithm that combines ingredients from meal plan recipes.
 */
interface ShoppingRepository {
    fun getAllItems(): Flow<List<ShoppingItem>>
    suspend fun addManualItem(name: String, quantity: Double, unit: String)
    suspend fun toggleItem(id: Long)
    suspend fun deleteItem(id: Long)
    suspend fun clearAll()
    suspend fun clearChecked()

    /**
     * Generate shopping list from meal plan recipes.
     * Algorithm:
     * 1. Get all unique recipe IDs for the week
     * 2. Collect all ingredients from those recipes
     * 3. Group by (name, unit) — case-insensitive
     * 4. Sum quantities within each group
     * 5. Clear existing auto-generated items
     * 6. Insert the combined list
     */
    suspend fun generateFromMealPlan(recipeIds: List<Long>)
}

class ShoppingRepositoryImpl @Inject constructor(
    private val shoppingItemDao: ShoppingItemDao,
    private val recipeDao: RecipeDao
) : ShoppingRepository {

    override fun getAllItems(): Flow<List<ShoppingItem>> =
        shoppingItemDao.getAll().map { entities -> entities.map { it.toDomain() } }

    override suspend fun addManualItem(name: String, quantity: Double, unit: String) {
        shoppingItemDao.insert(
            ShoppingItemEntity(
                name = name,
                quantity = quantity,
                unit = unit,
                isManual = true
            )
        )
    }

    override suspend fun toggleItem(id: Long) = shoppingItemDao.toggleChecked(id)

    override suspend fun deleteItem(id: Long) = shoppingItemDao.delete(id)

    override suspend fun clearAll() = shoppingItemDao.clearAll()

    override suspend fun clearChecked() = shoppingItemDao.clearChecked()

    override suspend fun generateFromMealPlan(recipeIds: List<Long>) {
        // Collect all ingredients from the planned recipes
        val allIngredients = recipeIds.flatMap { recipeId ->
            recipeDao.getIngredientsForRecipeOnce(recipeId).map { ingredient ->
                Triple(ingredient.name, ingredient.quantity, ingredient.unit) to recipeId
            }
        }

        // Group by (lowercased name, lowercased unit) and sum quantities.
        // This combines "2 cups flour" + "1 cup flour" into "3 cups flour"
        // but keeps "100g butter" and "2 tbsp butter" separate (different units).
        data class Key(val name: String, val unit: String)

        val combined = allIngredients
            .groupBy { (ingredient, _) -> Key(ingredient.first.lowercase(), ingredient.third.lowercase()) }
            .map { (key, entries) ->
                ShoppingItemEntity(
                    name = entries.first().first.first, // preserve original casing from first occurrence
                    quantity = entries.sumOf { it.first.second },
                    unit = entries.first().first.third, // preserve original unit casing
                    isManual = false,
                    sourceRecipeId = entries.first().second
                )
            }

        // Clear old auto-generated items, then insert the new combined list
        shoppingItemDao.clearAutoGenerated()
        shoppingItemDao.insertAll(combined)
    }

    private fun ShoppingItemEntity.toDomain() = ShoppingItem(
        id = id,
        name = name,
        quantity = quantity,
        unit = unit,
        isChecked = isChecked,
        sourceRecipeId = sourceRecipeId,
        isManual = isManual
    )
}
