package com.recipenotes.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.recipenotes.data.local.entity.ShoppingItemEntity
import kotlinx.coroutines.flow.Flow

/**
 * DAO for shopping list operations.
 * Items are ordered: unchecked first, then checked, alphabetically within each group.
 */
@Dao
interface ShoppingItemDao {

    @Query("SELECT * FROM shopping_items ORDER BY isChecked ASC, name ASC")
    fun getAll(): Flow<List<ShoppingItemEntity>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(item: ShoppingItemEntity): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(items: List<ShoppingItemEntity>)

    @Update
    suspend fun update(item: ShoppingItemEntity)

    /** Toggle checked state efficiently without loading the full entity */
    @Query("UPDATE shopping_items SET isChecked = NOT isChecked WHERE id = :id")
    suspend fun toggleChecked(id: Long)

    @Query("DELETE FROM shopping_items WHERE id = :id")
    suspend fun delete(id: Long)

    /** Clear all items */
    @Query("DELETE FROM shopping_items")
    suspend fun clearAll()

    /** Clear only checked items (user finished buying those) */
    @Query("DELETE FROM shopping_items WHERE isChecked = 1")
    suspend fun clearChecked()

    /** Clear auto-generated items (before regenerating from meal plan) */
    @Query("DELETE FROM shopping_items WHERE isManual = 0")
    suspend fun clearAutoGenerated()
}
